# Generated by Django 6.0.4 on 2026-04-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_booking_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Стол', 'verbose_name_plural': 'Столики'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Слот времени', 'verbose_name_plural': 'Слоты времени'},
        ),
    ]
