# Generated by Django 6.0.4 on 2026-04-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_table_options_alter_timeslot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Слот времени', 'verbose_name_plural': 'Слоты времени'},
        ),
    ]
